[package]
name = "contagion"
version = "0.1.0"
authors = ["ian <ianmccall93@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.10.0"
sdl2 = "0.32.1"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
default-features = false